feat: logic for atoma p2p for gossip nodes public urls
atoma-network/atoma-node pull request #286
Opened 2024-12-15 19:42 UTC by jorgeantonio21

2025-01-16 10:51 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +        if !response.address.starts_with("http://") && !response.address.starts_with("https://") {
Good observation !

2025-01-16 10:59 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                if let Err(e) = self
I removed this logic and added:

```rs
self.swarm
                    .behaviour_mut()
                    .gossipsub
                    .report_message_validation_result(message_id, propagation_source, gossipsub::MessageAcceptance::Accept)?;
```

2025-01-16 11:00 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                if let Err(e) = self
I believe in case the previous validation steps error, the gossipsub will automatically not propagate the message. Or should I enforce it through the `report_message_validation_result` to be `MessageAcceptance::Reject`?

2025-01-16 11:15 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +    gossipsub: gossipsub::Behaviour,
Thank you, this is very helpful. I added the kademlia and mdns behaviors back to the atoma-p2p-service. I believe `libp2p` internally handles all discovery/updates on the DHT and the subsequent interactions with the `gossipsub` layer. For this reason, I didn't add any further logic for event handling. Let me know if my assumptions are correct, or there needs to be more work done here.

2025-01-21 05:20 UTC, sdbondi commented on atoma-p2p/src/service.rs
> +                    .validation_mode(gossipsub::ValidationMode::Strict)
You need to add validate_message here
https://docs.rs/gossipsub/latest/gossipsub/struct.GossipsubConfig.html#method.validate_messages

2025-01-21 05:20 UTC, sdbondi commented on atoma-p2p/src/service.rs
> +                if let Err(e) = self
You always need to provide a resolution to the message - so should explicitly reject in the error case.

2025-01-21 05:22 UTC, sdbondi commented on atoma-p2p/src/service.rs
> +    gossipsub: gossipsub::Behaviour,
That's correct, essentially kad takes care of connecting to neighbours and discovering public addresses. These are then available to gossipsub.

2025-01-21 09:21 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                    .validation_mode(gossipsub::ValidationMode::Strict)
Oh nice one, there it goes

2025-01-21 09:33 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                if let Err(e) = self
I added some more logic for this

2025-01-21 09:36 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                let message_acceptance =
@sdbondi I added here error handling for message validation, and providing the acceptance criteria resulting from it, which is then passed below in the `report_message_validation_result`. How does this look like ?

2025-01-21 09:36 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                self.swarm
@sdbondi also added a `report_message_validation_result` to always accept requests for node addresses, as if I understand correctly, otherwise this message would not be propagated to other nodes.

2025-01-21 09:46 UTC, sdbondi commented on atoma-p2p/src/service.rs
> +                self.swarm
That is correct - however since gossipsub gossips the message to all subscribers, you probably don't want to use it for this part of the protocol. i.e. a single request will arrive at all subscribers (i.e all nodes) and will result in all nodes sending a response to all nodes. I assume that all nodes also send a request. $O(n^2)$ message complexity.

https://docs.rs/libp2p-request-response/latest/libp2p_request_response/ might be what you're looking for

2025-02-04 17:07 UTC, maschad requested changes
I'm still not convinced having p2p nodes register their public url is an effective mechanism for [peer routing](https://docs.libp2p.io/concepts/discovery-routing/overview/#peer-routing) 

If we are going to be using Kademlia DHTs for discovery this seems counter intuitive, nodes should be located by their [PeerID](https://docs.libp2p.io/concepts/fundamentals/peers/#peer-id)

It may be useful to examine how [Kademlia](https://pl-launchpad.io/curriculum/libp2p/dht/) works so that this is clearer

2025-02-04 17:07 UTC, maschad commented on atoma-p2p/src/timer.rs
> +                    duration_until_next_heartbeat(USAGE_METRICS_HEARTBEAT_INTERVAL);
This `duration_until_next_heartbeat` seems a bit excessive since this is a heartbeat system, we can just use a fixed interval sleep

```rust
        tokio::time::sleep(USAGE_METRICS_HEARTBEAT_INTERVAL).await;
```

2025-02-04 21:38 UTC, jorgeantonio21 commented on atoma-p2p/src/timer.rs
> +                    duration_until_next_heartbeat(USAGE_METRICS_HEARTBEAT_INTERVAL);
I agree, I will refactor this logic to be simpler and send messages every fixed interval (without any additional node synchronization).

2025-02-04 21:58 UTC, jorgeantonio21 commented on atoma-p2p/src/config.rs
> +    pub seed_nodes: Vec<String>,
This makes a lot of sense. Are these valid bootstrap that we can leverage ?

2025-02-04 22:37 UTC, maschad commented on atoma-p2p/src/config.rs
> +    pub seed_nodes: Vec<String>,
Yes they are, they are well connected nodes so it gives us access to an already rich DHT

2025-02-05 01:09 UTC, maschad requested changes
Awesome work on this @jorgeantonio21 🚀 

Looking good but left some comments

2025-02-05 01:09 UTC, maschad commented on atoma-p2p/src/service.rs
> +            GossipMessage::UsageMetrics(usage_metrics) => {
Do we intend to gossip other types of messages for the time being? Otherwise I don't think `UsageMetrics` needs to be an enum here, we can just use the type as done [here](https://github.com/atoma-network/atoma-node/pull/286/files#diff-f558264be9dc74d18752e874e9306be2942281ddfc84762ae59c17ae15b74d64R730)

2025-02-05 01:09 UTC, maschad commented on atoma-p2p/src/service.rs
> +    SignHashedMessageError(String),
How's this different than the [`SignatureError`](https://github.com/atoma-network/atoma-node/pull/286/files#diff-f558264be9dc74d18752e874e9306be2942281ddfc84762ae59c17ae15b74d64R787) ?

2025-02-05 01:09 UTC, maschad commented on atoma-p2p/src/service.rs
> +    GossipsubBuildError(String),
These two errors seems to address the same thing

2025-02-05 01:09 UTC, maschad commented on atoma-p2p/src/service.rs
> +    pub async fn validate_usage_metrics_message(
Let's an integration test for this given it's a combination of all of the functions

2025-02-05 07:57 UTC, jorgeantonio21 commented on atoma-p2p/src/config.rs
> +    pub seed_nodes: Vec<String>,
If other networks are using them for bootstrapping, how can they only bootstrap for our nodes/clients ? Through gossip sub topic (I imagine there is no uniqueness requirements for it).

2025-02-05 09:27 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +            .with_tcp(
Yeah, I believe so too. I was wondering if we would need in extreme scenarios (where nodes don't support `QUIC` for some reason) and could fallback to `TCP`. But I agree, let's move with only `QUIC`

2025-02-05 09:40 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +                        _ => {}
Are all these the events to handle ? If I understand correctly gossipsub already integrates kademlia for peer discovery, so there seems to not be much to do on that front..

2025-02-05 10:01 UTC, jorgeantonio21 commented on atoma-p2p/src/config.rs
> +    pub seed_nodes: Vec<String>,
Also, I doubt these nodes will subscribe to our gossipsub topics, so I am unsure this will be of any help for now.

2025-02-05 10:06 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +            GossipMessage::UsageMetrics(usage_metrics) => {
Yes, I do believe we want to add other gossip message types

2025-02-05 10:10 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +    GossipsubBuildError(String),
Addressed

2025-02-05 15:57 UTC, maschad commented on atoma-p2p/src/config.rs
> +    pub seed_nodes: Vec<String>,
Before a peer can subscribe to a topic it must find other peers and establish network connections with them. The pub/sub system doesn’t have any way to discover peers by itself.  The main purpose of boostrapping is to gain an overview of the network to accelerate peer discovery, gossipsub is not a peer discovery mechanism.

2025-02-05 16:14 UTC, maschad commented on atoma-p2p/src/service.rs
> +                        _ => {}
That's inaccurate, one has to explicitly add them when the `Discovered` event is emitted as you can see the [discovered_nodes](https://github.com/libp2p/rust-libp2p/blob/master/protocols/mdns/src/behaviour.rs#L180) is not merged into the gossipsub nor Kademlia properties, which is why in this [example](https://github.com/libp2p/rust-libp2p/blob/master/examples/distributed-key-value-store/src/main.rs#L93) it's done explicitly

2025-02-05 17:03 UTC, maschad commented on atoma-p2p/src/service.rs
> +        let _usage_metrics_url = Url::parse(&usage_metrics.node_public_url).map_err(|e| {
I don't think it's sufficient to check if the url has a valid format, I think for now we should have an allow list of set urls providers who can join the mesh and report and remove any peers who have URLs outside that which try to subscribe. This can later be revisited as we define more rigid [peer scoring](https://github.com/libp2p/specs/blob/master/pubsub/gossipsub/gossipsub-v1.1.md#peer-scoring)

2025-02-05 19:04 UTC, maschad commented on atoma-p2p/src/service.rs
> +
We should also include the [identify behaviour](https://github.com/libp2p/rust-libp2p/blob/56691dbc33de82e221da14ccea5edc04074e94c4/examples/identify/README.md#L4) as a part of the config

2025-02-06 10:15 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +        let _usage_metrics_url = Url::parse(&usage_metrics.node_public_url).map_err(|e| {
That's a great idea, I have created an issue for this. So that we can address it later

2025-02-06 10:17 UTC, jorgeantonio21 commented on atoma-p2p/src/service.rs
> +        let _usage_metrics_url = Url::parse(&usage_metrics.node_public_url).map_err(|e| {
See #390

2025-02-06 17:32 UTC, maschad reviewed
LGTM minus this one comment https://github.com/atoma-network/atoma-node/pull/286#discussion_r1945153329 Great job @jorgeantonio21  🚀

2025-02-06 21:54 UTC, maschad approved these changes
Excellent work!

2025-02-06 22:49 UTC, merged